language: php
php:
  - 7.0
  - 5.5
  - 5.6
  - 7.1
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true

before_script:
  - composer install --no-interaction
  - mkdir -p build/logs

script:
  - composer code-style
  - vendor/bin/phpunit --coverage-clover=build/logs/clover.xml --coverage-text
